language: node_js
cache:
  directories:
  - node_modules
node_js:
    - "6"
    - "5"
    - "4"
    - "0.12"
after_success:
  - cat ./test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js